# Generated by Django 5.1.4 on 2024-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default=None, max_length=30, verbose_name="Name"),
                ),
                (
                    "name_de",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_pt",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_cs",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_ja",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_plural",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_de",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_en",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_fr",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_it",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_es",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_pt",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_cs",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_ja",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_de",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_en",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_fr",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_it",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_es",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_pt",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_cs",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "abbreviation_ja",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        blank=True,
                        choices=[("kg", "Kilogram"), ("l", "Liter")],
                        max_length=2,
                        null=True,
                        verbose_name="SI Base Unit",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        max_digits=19,
                        null=True,
                        verbose_name="Conversion factor",
                    ),
                ),
                (
                    "unit_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("imp.", "Imperial"),
                            ("US", "US customary"),
                            ("Metric", "Metric"),
                            ("Shakkanhou", "Shakkanhō"),
                            ("", ""),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Unit System",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name__exact", ""), _negated=True),
                        name="units_unit_non_empty_name",
                    ),
                    models.UniqueConstraint(
                        fields=("name", "unit_system"),
                        name="units_unit_unique_combination_name",
                    ),
                    models.UniqueConstraint(
                        fields=("name_plural", "unit_system"),
                        name="units_unit_unique_combination_name_plural",
                    ),
                    models.UniqueConstraint(
                        fields=("abbreviation", "unit_system"),
                        name="units_unit_unique_combination_abbreviation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("conversion_factor__gt", 0)),
                        name="units_unit_conversion_factor_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("base_unit__isnull", False),
                                ("conversion_factor__isnull", False),
                            ),
                            models.Q(
                                ("base_unit__isnull", True),
                                ("conversion_factor__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="units_unit_base_unit_requires_conversion_factor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("base_unit__isnull", True),
                            ("base_unit__in", ["kg", "l"]),
                            _connector="OR",
                        ),
                        name="units_unit_base_unit_is_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("unit_system__isnull", True),
                            (
                                "unit_system__in",
                                ["imp.", "US", "Metric", "Shakkanhou", ""],
                            ),
                            _connector="OR",
                        ),
                        name="units_unit_unit_system_is_valid",
                    ),
                ],
            },
        ),
    ]
