# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: name-tests-test
        args: ["--django"]
      - id: mixed-line-ending
        args: [--fix=no]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "" # Use the sha / tag you want to point at
  #   hooks:
  #       - id: mypy
  #         args: [--ignore-missing-imports] # --no-strict-optional,
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: "v0.32.0" # Use the sha / tag you want to point at
    hooks:
      - id: yapf
        args: [] # no interactive
        additional_dependencies: [toml]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks