services:
  db:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    image: zest/postgres:latest
    # image: postgres
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_PORT=${SQL_PORT}
    # ports:
    #   - "${SQL_PORT}:${SQL_PORT}"

  cache:
    build:
      context: ./docker
      dockerfile: redis.Dockerfile
    image: zest/redis:latest  # Optional tag for clarity    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: zest/nginx:latest
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 1337:80

  backend:
    image: zest/backend:latest
    user: "${UID}:${GID}"
    working_dir: /code/backend/
    build:
      context: ./backend/
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -c config/gunicorn/dev.py
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_AUTH_MODE=${DJANGO_AUTH_MODE}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - TESTFLAGS=${TESTFLAGS} 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - nginx