services:
  backend:
    healthcheck:
      # test: ["CMD", "systemctl", "status", "postgresql"] # Replace with your check
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE} -h localhost"]
      interval: 1s
      timeout: 5s
      retries: 10
    image: zest/backend:latest
    user: "zest:root"
    working_dir: /code/backend/
    build:
      context: .
      dockerfile: docker/main.Dockerfile
      args:
        UID: "${UID}"
        GID: "${GID}"
        POSTGRES_DB: ${SQL_DATABASE}
        POSTGRES_USER: ${SQL_USER}
        POSTGRES_PW: ${SQL_PASSWORD}
        POSTGRES_PORT: ${SQL_PORT}
    command: gunicorn -c config/gunicorn/dev.py
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_AUTH_MODE=${DJANGO_AUTH_MODE}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=localhost
      - SQL_PORT=${SQL_PORT}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - TESTFLAGS=${TESTFLAGS}
    volumes:
      - .:/code
    ports:
      - "6379:6379"
      - 1337:80
      - "8000:8000"
