# Generated by Django 5.1.4 on 2024-12-21 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "name_de",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "name_es",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "name_cs",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "name_ja",
                    models.CharField(max_length=150, null=True, verbose_name="Name"),
                ),
                (
                    "wiki_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Wikidata ID",
                    ),
                ),
                (
                    "openfoodfacts_key",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="OpenFoodFacts Key",
                    ),
                ),
                (
                    "usda_nbd_ids",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="USDA NBD Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_it",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_pt",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_cs",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ja",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FoodNameSynonyms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("language", models.CharField(max_length=2)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synonyms",
                        to="foods.food",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Synonym",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MeasuredNutrient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "min",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Min"
                    ),
                ),
                (
                    "max",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Max"
                    ),
                ),
                (
                    "median",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Median"
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="foods.food",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrient",
                "verbose_name_plural": "Nutrients",
            },
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Name"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="units.unit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrient",
                "verbose_name_plural": "Nutrients",
            },
        ),
    ]
