# Generated by Django 5.1.4 on 2024-12-30 12:03

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_de"], name="gin_index_name_de", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_en"], name="gin_index_name_en", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_fr"], name="gin_index_name_fr", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_it"], name="gin_index_name_it", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_es"], name="gin_index_name_es", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_pt"], name="gin_index_name_pt", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_cs"], name="gin_index_name_cs", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_ja"], name="gin_index_name_ja", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="gin_index_name", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="foodnamesynonyms",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="gin_index_food_synonyms",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
