version: "3"

vars:
  ZEST_ENV: dev

env:
  ZEST_ENV: "{{.ZEST_ENV}}"

tasks:
  dev:rebuild:
    desc: "Rebuild docker image"
    cmds:
      - docker compose up -w --build

  dev:
    desc: "Run development environment with hot reload"
    dotenv:
      - .env.dev
    vars:
      ZEST_ENV: dev
      CODE_VERSION:
        sh: date +%s%N
    cmds:
      - docker compose up -w --build

  dev:detach:
    desc: "Run development environment in background"
    dotenv:
      - .env.dev
    vars:
      ZEST_ENV: dev
      CODE_VERSION:
        sh: date +%s%N
    cmds:
      - docker compose up -d --build

  dev:down:
    desc: "Stop development environment"
    dotenv:
      - .env.dev
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml down --volumes --remove-orphans --rmi local

  dev:init:
    desc: "Init development environment with hot reload"
    dotenv:
      - .env.dev
    vars:
      ZEST_ENV: dev
      CODE_VERSION:
        sh: date +%s%N
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm backend alembic upgrade head
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm backend python scripts/install_fixtures.py --fixture fixtures/recipe_categories.json
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm backend python scripts/install_fixtures.py --fixture fixtures/units.json
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm backend python scripts/install_fixtures.py --fixture fixtures/foods.json
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm backend python scripts/index_data.py
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm backend python scripts/index_data.py

  db:psql:
    desc: "Connect to database with psql"
    cmds:
      - docker compose exec db psql -U postgres -d app

  test:
    dotenv:
      - .env.test
    vars:
      ZEST_ENV: test
      CODE_VERSION:
        sh: date +%s%N
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.test.yml up -d db
      - docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm backend alembic upgrade head
      - docker compose -f docker-compose.yml -f docker-compose.test.yml up --build --exit-code-from backend
      - docker compose -f docker-compose.yml -f docker-compose.test.yml down -v

  test:down:
    desc: "Bring down test related containers"
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml down --volumes --remove-orphans --rmi local


