#!/usr/bin/env bash
set -e

echo "Initializing database with env vars..."
echo "${POSTGRES_USER}, $POSTGRES_PASSWORD, $POSTGRES_DB"

psql -v ON_ERROR_STOP=1 <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
    CREATE ROLE ${POSTGRES_USER}
      LOGIN
      PASSWORD '${POSTGRES_PASSWORD}';
  END IF;
END
\$\$;

GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
EOSQL
