"""Initial FK Migration

Revision ID: fe4f67eb747e
Revises: 2aaece060e88
Create Date: 2026-03-22 09:51:20.876673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4f67eb747e'
down_revision: Union[str, Sequence[str], None] = '2aaece060e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ingredient_groups', 'recipe_revisions', ['recipe_revision_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ingredients', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'ingredients', 'ingredient_groups', ['ingredient_group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'instruction_groups', 'recipe_revisions', ['recipe_revision_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_categories_association', 'recipe_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_categories_association', 'recipe_revisions', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_revisions', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipes', 'recipes', ['original_recipe_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recipes', 'recipe_revisions', ['latest_revision_id'], ['id'])
    op.create_foreign_key(None, 'recipes', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_favorite_recipes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_favorite_recipes', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorite_recipes', type_='foreignkey')
    op.drop_constraint(None, 'user_favorite_recipes', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipe_revisions', type_='foreignkey')
    op.drop_constraint(None, 'recipe_categories_association', type_='foreignkey')
    op.drop_constraint(None, 'recipe_categories_association', type_='foreignkey')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_constraint(None, 'instruction_groups', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'ingredient_groups', type_='foreignkey')
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    # ### end Alembic commands ###
