# Generated by Django 5.1.4 on 2024-12-21 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foods", "0001_initial"),
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IngredientGroup",
                "verbose_name_plural": "IngredientGroups",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="InstructionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "InstructionGroup",
                "verbose_name_plural": "InstructionGroups",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipe_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "original_recipe_id",
                    models.UUIDField(blank=True, default=None, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("de", "German"),
                            ("en", "English"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("es", "Spanish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("ja", "Japanese"),
                        ],
                        default=("de", "German"),
                        max_length=2,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtitle"
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Difficulty Not Set"),
                            (1, "Difficulty Easy"),
                            (2, "Difficulty Medium"),
                            (3, "Difficulty Hard"),
                        ],
                        default=0,
                        verbose_name="Difficulty",
                    ),
                ),
                ("servings", models.PositiveSmallIntegerField(verbose_name="Servings")),
                (
                    "prep_time",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Preparation time"
                    ),
                ),
                (
                    "cook_time",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Cooking time"
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Source name",
                    ),
                ),
                (
                    "source_page",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Source page"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="Source URL"),
                ),
                (
                    "owner_comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                ("private", models.BooleanField(default=True, verbose_name="Private")),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="RecipeCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_de",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_es",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_pt",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_cs",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ja",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_plural",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_de",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_it",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_es",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_pt",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_cs",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
                (
                    "name_plural_ja",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (plural)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Category",
                "verbose_name_plural": "Recipe Categories",
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="(Lower) Amount"
                    ),
                ),
                (
                    "amount_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Max. Amount",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="Details"),
                ),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="foods.food"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="units.unit"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.ingredientgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="recipes.instructiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction",
                "verbose_name_plural": "Instructions",
                "ordering": ["position"],
            },
        ),
    ]
